In [2]:
#import packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#display all the columns and formatting float numbers
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

In [3]:
df = pd.read_csv('ecommerce_sales_customer_analytics_150k.csv')

In [4]:
#number of rows and columns of dataframe
df.shape

(138116, 46)

In [5]:
#information on the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), object(27)
memory usage: 47.6+ MB

In [6]:
#return the first 5 rows of the dataframe
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,customer_type,customer_city,customer_state,customer_country,region,customer_postal_code,payment_method,payment_status,currency,shipping_method,warehouse,delivery_days,estimated_delivery_days,delivery_status,return_status,return_reason,customer_rating,review_sentiment,customer_review,marketing_channel,campaign_name,coupon_code,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,Loyal,Lake Williamberg,Texas,USA,South,86040,Digital Wallet,Paid,USD,Standard,WH-003,3.00,3.00,On Time,NaN,NaN,3.50,Positive,Satisfied with the purchase.,Direct,Default_Campaign,NaN,94,44,5,"1,350.19",477.89,61.07,12.03,945.40,588.33,345.04,36.50,"12,459.68",True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,Loyal,Kristyport,Baden-Württemberg,Germany,South,62538,Debit Card,Pending,EUR,Economy,WH-005,10.00,10.00,On Time,NaN,NaN,3.60,Positive,Good value for money.,Direct,Default_Campaign,NaN,201,171,8,"3,144.64","1,456.06",320.83,9.00,"2,018.41","2,031.88",-22.47,-1.11,"13,032.48",True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,Loyal,Singletonhaven,New York,USA,East,19993,Cash on Delivery,Paid,USD,Express,WH-015,3.00,3.00,On Time,NaN,NaN,4.30,Positive,Good product. Works as expected.,YouTube,NaN,NaN,46,16,5,522.81,97.30,29.79,13.05,468.35,257.73,197.57,42.18,"6,159.44",True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,Loyal,Wigginsstad,North Carolina,USA,South,66329,Debit Card,Paid,USD,Express,WH-010,2.00,2.00,On Time,NaN,NaN,3.50,Positive,Satisfied with the purchase.,Email Marketing,NaN,NaN,54,10,2,544.62,53.34,34.39,20.85,546.52,277.84,247.83,45.35,"5,638.30",True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,Loyal,New Michaelton,Gujarat,India,West,77306,Digital Wallet,Paid,INR,Standard,WH-013,6.00,5.00,Delayed,NaN,NaN,3.00,Neutral,Mixed feelings about this purchase.,Direct,NaN,NaN,278,147,6,"2,474.52",133.63,421.35,23.03,"2,785.27","1,231.88","1,530.36",54.94,"13,240.10",True,8

In [7]:
#return the last 5 rows of the dataframe
df.tail()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,customer_type,customer_city,customer_state,customer_country,region,customer_postal_code,payment_method,payment_status,currency,shipping_method,warehouse,delivery_days,estimated_delivery_days,delivery_status,return_status,return_reason,customer_rating,review_sentiment,customer_review,marketing_channel,campaign_name,coupon_code,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,Loyal,Lake Danielville,New York,USA,East,60282,Credit Card,Paid,USD,Standard,WH-006,7.00,7.00,On Time,NaN,NaN,3.90,Positive,Met my expectations. Would recommend.,Organic Search,Default_Campaign,NaN,22,16,1,212.83,8.84,14.28,6.15,224.42,101.77,116.50,51.91,"18,182.63",True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,Loyal,Debrafort,California,USA,West,54044,Digital Wallet,Refunded,USD,Standard,WH-001,NaN,NaN,Cancelled,Returned,Size Issue,NaN,NaN,NaN,Instagram,NaN,NaN,0,0,7,"2,104.32",0.00,147.30,9.18,"2,260.80","1,246.73","1,004.89",44.45,"10,004.74",True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,Loyal,Mcmillanshire,England,UK,North,59622,PayPal,Failed,GBP,Economy,WH-003,NaN,NaN,Cancelled,NaN,NaN,NaN,NaN,NaN,Direct,NaN,NaN,0,0,8,"1,861.85",0.00,372.37,26.94,"2,261.16",970.95,"1,263.27",55.87,"16,442.68",True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,Loyal,South Joshuafort,Ohio,USA,Central,84607,Debit Card,Paid,USD,Same Day,WH-010,1.00,0.00,Delayed,NaN,NaN,3.30,Neutral,Quality could be improved.,Google Ads,NaN,SAVE39,208,7,13,"2,040.01",174.60,130.58,84.39,"2,080.38","1,042.40",953.59,45.84,"8,047.00",True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,Loyal,Brianview,California,USA,West,88333,Digital Wallet,Paid,USD,Standard,WH-013,5.00,5.00,On Time,NaN,NaN,4.10,Positive,"Product is okay, nothing special but works.",Organic Search,NaN,NaN,157,26,6,"1,878.14",417.27,102.26,9.09,"1,572.22",884.46,678.67,43.17,"4,107.38",True,5

In [8]:
#statistical information for numerical columns
df.describe()

,customer_age,customer_postal_code,delivery_days,estimated_delivery_days,customer_rating,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,customer_order_count
count,"138,116.00","138,116.00","113,559.00","113,559.00","113,559.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00","138,116.00"
mean,45.86,"50,210.89",4.56,4.30,3.68,103.99,51.93,5.62,"1,375.38",237.62,122.46,22.28,"1,282.50",708.90,551.32,45.07,"8,971.64",6.99
std,16.47,"28,569.77",2.81,2.59,0.48,115.18,73.22,3.37,"1,291.01",378.78,140.94,16.02,"1,169.27",730.04,516.30,13.12,"4,430.51",2.44
min,18.00,516.00,0.00,0.00,1.60,0.00,0.00,1.00,6.31,0.00,0.34,0.00,5.80,1.97,"-1,281.59",-59.55,22.55,1.00
25%,32.00,"25,509.00",2.00,2.00,3.40,17.00,3.00,3.00,458.92,26.33,34.65,9.82,448.20,207.67,190.76,38.88,"5,713.57",5.00
50%,46.00,"50,183.00",4.00,4.00,3.70,70.00,25.00,5.00,995.73,103.28,77.01,19.19,950.76,478.95,408.39,46.99,"8,392.53",7.00
75%,60.00,"74,898.00",7.00,6.00,4.00,151.00,71.00,8.00,"1,871.20",277.12,156.20,30.75,"1,744.58",953.76,752.84,53.77,"11,651.03",9.00
max,74.00,"99,950.00",14.00,10.00,5.00,"1,621.00","1,063.00",24.00,"16,051.19","6,759.02","2,091.52",149.52,"16,218.00","9,963.41","7,083.68",77.59,"30,268.44",20.00

In [9]:
#statistical information for text columns
df.describe(include= object).T

                    count  unique                    top    freq
order_id           138116  138116             ORD-528577       1
order_date         138116    1826             2025-12-30     143
order_time         138116   68991               14:55:55      11
order_status       138116       4              Completed  113559
sales_channel      138116       4             Mobile App   55318
customer_id        138116   24911            CUST-014687      19
customer_name      138116   21564             John Smith      97
gender             138116       3                 Female   66439
customer_segment   138116       4               Consumer   75636
customer_type      138116       3                  Loyal  129447
customer_city      138116   15516           Lake Michael     166
customer_state     138116      38           Pennsylvania    9148
customer_country   138116       7                    USA   82600
region             138116       5                  South   43990
payment_method     138116       7            Credit Card   41460
payment_status     138116       4                   Paid  104250
currency           138116       7                    USD   82600
shipping_method    138116       4               Standard   62006
warehouse          138116      19                 WH-014    7447
delivery_status    138116       4                On Time   86916
return_status        9462       1               Returned    9462
return_reason        9462       8          Wrong Product    1237
review_sentiment   113559       3               Positive   78083
customer_review    113559      25  Good value for money.   12237
marketing_channel  138116      10         Organic Search   27742
campaign_name       54883      17       Default_Campaign   22989
coupon_code         27614      40                 SAVE39     731

In [10]:
#check the number of nulls in each column
df.isnull().sum()

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [11]:
#convert order_date data type to datetime
df['order_date'] = pd.to_datetime(df['order_date'], errors= 'coerce')

In [12]:
#filling nulls
df['return_status'] = df['return_status'].fillna('Not returned')
df['return_reason'] = df['return_reason'].fillna('N/A')
df['campaign_name'] = df['return_reason'].fillna('None')
df['coupon_code'] = df['return_reason'].fillna('None')

In [13]:
#check number of duplicate rows
df.duplicated().sum()

np.int64(0)

In [14]:
#check for duplicate order id
df['order_id'].duplicated().sum()

np.int64(0)

In [15]:
#check for inconsistent labelling and other data quality issues
df['order_status'].value_counts(dropna= 'false')

order_status
Completed    113559
Returned       9462
Cancelled      8398
Pending        6697
Name: count, dtype: int64

In [16]:
df['payment_status'].value_counts(dropna= 'false')

payment_status
Paid        104250
Pending      13975
Failed       10429
Refunded      9462
Name: count, dtype: int64

In [17]:
df['sales_channel'].value_counts(dropna= 'false')

sales_channel
Mobile App      55318
Website         48237
Marketplace     20698
Social Media    13863
Name: count, dtype: int64

In [18]:
df['delivery_status'].value_counts(dropna= 'false')

delivery_status
On Time      86916
Cancelled    24557
Delayed      16886
Early         9757
Name: count, dtype: int64

In [23]:
#check for inconsistencies between order and delivery status
pd.crosstab(
    df["order_status"],
    df["delivery_status"],
    margins= True
)

delivery_status  Cancelled  Delayed  Early  On Time     All
order_status
Cancelled             8398        0      0        0    8398
Completed                0    16886   9757    86916  113559
Pending               6697        0      0        0    6697
Returned              9462        0      0        0    9462
All                  24557    16886   9757    86916  138116

In [ ]:
#check for currency before calculating total revenue
df.groupby("currency").agg(
    order_count = ("order_id", "nunique"),
    net_sales = ("net_sales", "sum"),
    average_order_value = ("net_sales", "mean")
).round(2)

          order_count      net_sales  average_order_value
currency
AED              4172   5,165,973.41             1,238.25
AUD              6794   8,813,690.51             1,297.28
CAD              7015   9,198,848.48             1,311.31
EUR             11593  16,044,171.91             1,383.95
GBP             20235  27,963,200.79             1,381.92
INR              5707   7,718,287.28             1,352.42
USD             82600 102,230,091.36             1,237.65